// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iomfmbbinuipggfrnaha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvbWZtYmJpbnVpcGdnZnJuYWhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NDY0MjYsImV4cCI6MjA2MjEyMjQyNn0.Qn8eMLAOKEHfUn73Ku8bNpnGSfZjix1KYB76eHRnDCk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);